In [1]:
import os
import importlib
import time

import numpy as np
import pandas as pd

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import skimage
from skimage import transform as skimg_transform
#from skimage import io as img_io
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import transforms, utils, models
from torch.utils import data
from torch.utils.data.sampler import SubsetRandomSampler

import load_data
import model
import warnings

In [2]:
plt.style.use('Solarize_Light2')
warnings.filterwarnings('ignore')
%matplotlib inline
importlib.reload(load_data)
importlib.reload(model)

<module 'model' from '/home/uldo/work/kaggle/competitions/Humpback_Whale_Identification/code/model.py'>

In [3]:
#BATCH_SIZE = 100
#BATCH_SIZE = 32
#BATCH_SIZE = 200
#BATCH_SIZE = 128
#BATCH_SIZE = 64
BATCH_SIZE = 32
#IMAGE_W = 100
IMAGE_W = 256
#IMAGE_H = 100
IMAGE_H = 256

In [4]:
'''
class HWI_ConvNeuralNet(nn.Module):
    
    def __init__(self):
        super(HWI_ConvNeuralNet, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 6, 5, 1, 2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(6, 12, 5, 1, 2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.drop_out = nn.Dropout()
        self.out1 = nn.Linear(int(12 * IMAGE_W/4 * IMAGE_H/4), 900)
        self.out2 = nn.Linear(900, 1)
        
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)
        output = self.drop_out(x)
        output = self.out1(x)
        output = self.out2(output)
        #return output, x
        return output[:, 0]
        #return F.log_softmax(output, dim=1)
'''

'\nclass HWI_ConvNeuralNet(nn.Module):\n    \n    def __init__(self):\n        super(HWI_ConvNeuralNet, self).__init__()\n        self.conv1 = nn.Sequential(\n            nn.Conv2d(3, 6, 5, 1, 2),\n            nn.ReLU(),\n            nn.MaxPool2d(kernel_size=2)\n        )\n        self.conv2 = nn.Sequential(\n            nn.Conv2d(6, 12, 5, 1, 2),\n            nn.ReLU(),\n            nn.MaxPool2d(kernel_size=2)\n        )\n        self.drop_out = nn.Dropout()\n        self.out1 = nn.Linear(int(12 * IMAGE_W/4 * IMAGE_H/4), 900)\n        self.out2 = nn.Linear(900, 1)\n        \n    def forward(self, x):\n        x = self.conv1(x)\n        x = self.conv2(x)\n        x = x.view(x.size(0), -1)\n        output = self.drop_out(x)\n        output = self.out1(x)\n        output = self.out2(output)\n        #return output, x\n        return output[:, 0]\n        #return F.log_softmax(output, dim=1)\n'

In [5]:
class HWI_ConvNeuralNet(nn.Module):
    
    def __init__(self):
        super(HWI_ConvNeuralNet, self).__init__()
        
        self.conv1 = nn.Conv2d(3, 32, 7, padding=1)
        self.conv2_bn = nn.BatchNorm2d(32)
        self.pool = nn.MaxPool2d(2, 2)
        
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)        
        self.pool2 = nn.AvgPool2d(3, 3)
        
        self.fc1 = nn.Linear(64 * 4 * 4 * 16, 1024)
        #self.fc1 = nn.Linear(64, 1024)
        #self.fc2 = nn.Linear(1024, 5004)
        self.fc2 = nn.Linear(1024, 1)
        
        self.dropout = nn.Dropout(0.5)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        #print("forward, input x.size(): ", x.size())
        x = self.pool(F.relu(self.conv2_bn(self.conv1(x))))
        #print("forward, x.size() after self.pool(F.relu(self.conv2_bn(self.conv1(x)))): ", x.size())
        x = self.pool2(F.relu(self.conv2(x)))
        #print("forward, x.size() after self.pool2(F.relu(self.conv2(x))): ", x.size())
        x = x.view(-1, 64 * 4 * 4 * 16)
        #print("forward, x.size() after x.view(-1, 64 * 4 * 4 * 16): ", x.size())
        x = F.relu(self.fc1(x))
        #print("forward, x.size() after F.relu(self.fc1(x)): ", x.size())
        x = self.dropout(x)
        #print("forward, x.size() after self.dropout(x): ", x.size())
        x = self.fc2(x)
        #print("forward, x.size() after self.fc2(x): ", x.size())
        #x = self.fc3(x)
        x = self.sigmoid(x)
        #print("forward, x.size() after self.sigmoid(x): ", x.size())
        return x       

In [6]:
class HWI_ConvNeuralNet(nn.Module):
    
    def __init__(self):
        super(HWI_ConvNeuralNet, self).__init__()
        '''
        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 6, 5, 1, 2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(6, 12, 5, 1, 2),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2)
        )
        self.drop_out = nn.Dropout()
        self.out1 = nn.Linear(int(12 * IMAGE_W/4 * IMAGE_H/4), 900)
        self.out2 = nn.Linear(900, 1)
        '''
        self.conv1 = nn.Conv2d(3, 32, kernel_size=9, stride=2, padding=4)
        #self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=5, stride=2, padding=2)
        #self.fc1 = nn.Linear(int(IMAGE_H * IMAGE_W 131072 x 16), 1024)
        #self.fc1 = nn.Linear(524288 * 64, 1024)
        self.fc1 = nn.Linear(32768 * 16, 1024)
        self.fc2 = nn.Linear(1024, 32)
        self.pool = torch.nn.MaxPool2d(kernel_size=2, stride=2, padding=0)
        self.sigmoid = nn.Sigmoid()
        self.dropout = nn.Dropout(0.5)
        
        #forward, input x.size():  torch.Size([64, 3, 256, 256])
        #forward, after F.relu(self.conv1(x)) x.size():  torch.Size([64, 32, 128, 128])
        #forward, after self.pool(x) x.size():  torch.Size([64, 32, 64, 64])
        #forward, after F.relu(self.conv2(x)) x.size():  torch.Size([64, 64, 32, 32])
        #forward, after self.pool(x) x.size():  torch.Size([64, 64, 16, 16])
        #forward, after x.view(-1, 65536 * 16) x.size():  torch.Size([1, 1048576])
        #forward, after F.relu(self.fc1(x)) x.size():  torch.Size([1, 1024])
        #forward, after self.dropout x.size():  torch.Size([1, 1024])
        #forward, after self.fc2 x.size():  torch.Size([1, 1])
        #forward, after self.sigmoid(x) x.size():  torch.Size([1, 1])
        
    def forward(self, x):
        '''
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)
        output = self.drop_out(x)
        output = self.out1(x)
        output = self.out2(output)
        #return output, x
        return output[:, 0]
        '''
        #print("forward, input x.size(): ", x.size())
        
        x = F.relu(self.conv1(x))
        #print("forward, after F.relu(self.conv1(x)) x.size(): ", x.size())
        x = self.pool(x)
        #print("forward, after self.pool(x) x.size(): ", x.size())
        x = F.relu(self.conv2(x))
        #print("forward, after F.relu(self.conv2(x)) x.size(): ", x.size())
        x = self.pool(x)     
        #print("forward, after self.pool(x) x.size(): ", x.size())  
        x = x.view(-1, 32768 * 16)
        #print("forward, after x.view(-1, 65536 * 16) x.size(): ", x.size())
        x = F.relu(self.fc1(x))
        #print("forward, after F.relu(self.fc1(x)) x.size(): ", x.size())
        x = self.dropout(x)
        #print("forward, after self.dropout x.size(): ", x.size())
        x = self.fc2(x)
        #print("forward, after self.fc2 x.size(): ", x.size())
        x = self.sigmoid(x)
        #print("forward, after self.sigmoid(x) x.size(): ", x.size())
        return x
        

In [ ]:
resnet18 = models.resnet18(pretrained=True)

In [ ]:
resnet18

In [ ]:
features_num = resnet18.fc.in_features

In [ ]:
#resnet18.fc = nn.Linear(features_num, BATCH_SIZE)
#resnet18.fc = nn.Linear(BATCH_SIZE, 2048)
#resnet18.fc = nn.Linear(2048, BATCH_SIZE)
resnet18.fc = nn.Sigmoid()

In [7]:
class Rescale(object):
    """Rescale the image in a sample to a given size.

    Args:
        output_size (tuple or int): Desired output size. If tuple, output is
            matched to output_size. If int, smaller of image edges is matched
            to output_size keeping aspect ratio the same.
    """

    def __init__(self, output_size):
        assert isinstance(output_size, (int, tuple))
        self.output_size = output_size

    def __call__(self, sample):
        image, label = sample['image'], sample['label']

        orig_height, orig_width = image.shape[:2]
        if isinstance(self.output_size, int):
            if orig_height > orig_width:
                new_height, new_width = self.output_size * orig_height / orig_width, self.output_size
            else:
                new_height, new_width = self.output_size, self.output_size * orig_width / orig_height
        else:
            new_height, new_width = self.output_size

        new_height, new_width = int(new_height), int(new_width)

        img = skimg_transform.resize(image, (new_height, new_width))

        return {'image': img, 'label': label}

In [8]:
class UnifyRescale(object):
    
    def __init__(self, output_size=128):
        assert isinstance(output_size, int)
        self.output_size = output_size
        
    def __call__(self, sample):
        image, label = sample['image'], sample['label']

        img = skimg_transform.resize(image, (self.output_size, self.output_size))

        return {'image': img, 'label': label}

In [9]:
class RandomCrop(object):
    """Crop randomly the image in a sample.

    Args:
        output_size (tuple or int): Desired output size. If int, square crop
            is made.
    """

    def __init__(self, output_size):
        assert isinstance(output_size, (int, tuple))
        if isinstance(output_size, int):
            self.output_size = (output_size, output_size)
        else:
            assert len(output_size) == 2
            self.output_size = output_size

    def __call__(self, sample):
        image, label = sample['image'], sample['label']

        orig_height, orig_width = image.shape[:2]
        new_height, new_width = self.output_size

        top = np.random.randint(0, orig_height - new_height)
        left = np.random.randint(0, orig_width - new_width)

        image = image[top: top + new_height, left: left + new_width]

        return {'image': image, 'label': label}

In [10]:
class ToTensor(object):
    
    """Convert ndarrays in sample to Tensors."""
    def __init__(self, image_size=128):
        self.image_size = image_size

    def __call__(self, sample):
        image, label = sample['image'], sample['label']

        # swap color axis because
        # numpy image: H x W x C
        # torch image: C X H X W
        
        """ The original code didn't expect gray scale images """
        
        gray_scale_image = torch.zeros(
            [self.image_size, self.image_size]
        ).shape == image.shape
        if gray_scale_image:
            image = np.stack((image,) * 3, axis=-1)
        
        image = image.transpose((2, 0, 1))
        return {'image': torch.from_numpy(image), 'label': torch.tensor(label, dtype=torch.uint8)}

In [11]:
def show_whale_batch(sample_batched):
    """Show whales for a batch of samples."""
    images_batch = sample_batched['image']
    labels_batch = sample_batched['label']
    batch_size = len(images_batch)
    im_size = images_batch.size(2)

    grid = utils.make_grid(images_batch)
    plt.imshow(grid.numpy().transpose((1, 2, 0)))

    for i in range(batch_size):
        plt.title('Batch from dataloader')

In [12]:
def init_weights(submodule):
    if type(submodule) == nn.Linear:
        nn.init.xavier_uniform_(submodule.weight)
        submodule.bias.data.fill_(0.01)

In [13]:
def prepare_loaders(dataset, valid_train_ratio=0.6):
    dataset_size = len(dataset)
    print("dataset_size: ", dataset_size)

    validation_subset_size = int(dataset_size * (1 - valid_train_ratio))
    print("validation_subset_size: ", validation_subset_size)

    indices = list(range(dataset_size))
    validation_indices = np.random.choice(indices, size=validation_subset_size, replace=False)
    train_indices = list(set(indices) - set(validation_indices))

    train_sampler = SubsetRandomSampler(train_indices)
    validation_sampler = SubsetRandomSampler(validation_indices)
    
    dataset_sizes = {
            'train': len(train_indices),
            'validation': len(validation_indices)
        }

    #train_loader = data.DataLoader(dataset, batch_size=BATCH_SIZE, num_workers=1, sampler=train_sampler, pin_memory=True)
    train_loader = data.DataLoader(dataset, batch_size=BATCH_SIZE, num_workers=1, sampler=train_sampler)
    #validation_loader = data.DataLoader(dataset, batch_size=BATCH_SIZE, num_workers=1, sampler=validation_sampler, pin_memory=True)
    validation_loader = data.DataLoader(dataset, batch_size=BATCH_SIZE, num_workers=1, sampler=validation_sampler)
    loaders = {
            'train': train_loader,
            'validation': validation_loader
        }

    return loaders, dataset_sizes

In [14]:
def unfold_batch(batch):
    return batch['image'], batch['label']

In [15]:
def one_epoch_train(model, data_loader, criterion, optimizer):
    
    accuracy = 0.0
    total_loss = 0.0
    correct_predicted_total = 0.0
    
    for i, data_batch in enumerate(data_loader, 0):
        #print("one_epoch_model_process, len(data_batch): ", len(data_batch))
        #print("one_epoch_model_process, type(data_batch): ", type(data_batch))        
        
        inputs, labels = unfold_batch(data_batch)
        #print("one_epoch_model_process, inputs.size(): ", inputs.size())
        if inputs.size()[0] == BATCH_SIZE:
            
            #print("inputs: ", inputs)
            #print("labels: ", labels)
        
            inputs = inputs.to(device, dtype=torch.float)
            #labels = labels.to(device, dtype=torch.float)
            labels = labels.to(device, dtype=torch.long)
            optimizer.zero_grad()
        
            
            outputs = model(inputs)

            #print("outputs.size():\n", outputs.size())
            #print("labels.size():\n", labels.size())
            #print("outputs:\n", outputs)
            #print("outputs[:, 0]:\n", outputs[:, 0])
            #print("labels:\n", labels)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
        
            total_loss += loss.item() * inputs.size(0)
        
            predicted = outputs > 0
            #print("type(predicted): ", type(predicted))
            #print("predicted:\n", predicted)
            print("predicted.size():", predicted.size())
            print("predicted:\n", predicted)
            #total += labels.size(0)
            labels = labels.data.byte()
            print("\nlabels.size():", labels.size())
            print("labels:\n", labels)
            #print("predicted == labels:\n", predicted == labels)
            #sum_of_correct_predicted = torch.sum((predicted == labels).all(1))
            sum_of_correct_predicted = torch.sum((predicted == labels))
            print("\nsum_of_correct_predicted.size():\n", sum_of_correct_predicted.size())
            print("sum_of_correct_predicted:\n", sum_of_correct_predicted)
            
            item = sum_of_correct_predicted.item()
            print("\nitem.size(): ", item)
            print("item:\n", item)
            correct_predicted_total += item
        
    accuracy = correct_predicted_total
    
    #epoch_train_loss = total_loss / train_dataset_size
    #epoch_train_accuracy = correct_predicted_total / train_dataset_size
    return (total_loss, accuracy)

In [16]:
def validate(model, validation_loader, criterion):
    model.eval()
    with torch.no_grad():
        
        correct_predicted_total = 0.0
        total_loss = 0.0
        #total = 0.0
        
        for data_batch in validation_loader:
            inputs, labels = unfold_batch(data_batch)

            inputs = inputs.to(device, dtype=torch.float)
            #labels_as_float = labels.to(device, dtype=torch.float)
            #labels = labels.to(device, dtype=torch.uint8)
            labels = labels.to(device, dtype=torch.float)
            outputs = model(inputs)
            
            loss = criterion(outputs, labels)
            #loss = criterion(outputs, labels_as_float)
            total_loss += loss.item() * inputs.size(0)
            
            predicted = outputs > 0

            #total += labels.size(0)
            labels = labels.data.byte()
            #sum_of_correct_predicted = torch.sum((predicted == labels).all(1))
            sum_of_correct_predicted = torch.sum((predicted == labels))
            item = sum_of_correct_predicted.item()

            correct_predicted_total += item

        #accuracy = correct_predicted_total / total
        accuracy = correct_predicted_total
        

    return (total_loss, accuracy)

In [17]:
def one_epoch_validate(model, data_loader, criterion):
    model.eval()
    with torch.no_grad():
        
        correct_predicted_total = 0.0
        total_loss = 0.0

        for data_batch in data_loader:
            inputs, labels = unfold_batch(data_batch)
            if inputs.size()[0] == BATCH_SIZE:

                inputs = inputs.to(device, dtype=torch.float)
                #labels = labels.to(device, dtype=torch.float)
                labels = labels.to(device, dtype=torch.long)
                outputs = model(inputs)
            
                loss = criterion(outputs, labels)
                total_loss += loss.item() * inputs.size(0)
            
                predicted = outputs > 0
            
                labels = labels.data.byte()
                sum_of_correct_predicted = torch.sum((predicted == labels))
                item = sum_of_correct_predicted.item()

                correct_predicted_total += item

        accuracy = correct_predicted_total        

    return (total_loss, accuracy)

In [18]:
def one_epoch_model_process(model, loader, criterion, optimizer=None):
    accuracy = 0.0
    total_loss = 0.0

    for data_batch in loader:
        print("one_epoch_model_process, len(data_batch): ", len(data_batch))
        print("one_epoch_model_process, type(data_batch): ", type(data_batch))
        if len(data_batch) == BATCH_SIZE:
            inputs, labels = unfold_batch(data_batch)
            inputs = inputs.to(device, dtype=torch.float)
            labels = labels.to(device, dtype=torch.float)
            outputs = model(inputs)[:, 0]
            
            loss = criterion(outputs, labels)
            if optimizer:
                loss.backward()
                optimizer.step()
            total_loss += loss.item() * inputs.size(0)
            
            predicted = outputs > 0

            labels = labels.data.byte()
            #torch_sum_of_correct_predicted = torch.sum((predicted == labels).all(1))
            torch_sum_of_correct_predicted = torch.sum((predicted == labels))
            correct_predicted = torch_sum_of_correct_predicted.item()

    accuracy += correct_predicted        

    return (total_loss, accuracy)

In [19]:
def train_model(num_of_epoch, model, dataset_loaders, dataset_sizes, criterion, optimizer):
    torch.cuda.empty_cache()
    since = time.time()
    
    train_loader = dataset_loaders['train']
    validation_loader = dataset_loaders['validation']
    train_dataset_size = dataset_sizes['train']
    validation_dataset_size = dataset_sizes['validation']
    
    best_model_accuracy = 0.0
    best_model_weights = model.state_dict()
    
    train_losses = []
    train_accuracies = []
    validation_losses = []
    validation_accuracies = []
    
    for epoch in range(num_of_epoch):
        
        train_loss, train_accuracy = one_epoch_train(model, train_loader, criterion, optimizer)
        train_losses.append(train_loss / train_dataset_size)
        train_accuracies.append(train_accuracy / train_dataset_size)
        
        validation_loss, validation_accuracy = one_epoch_validate(model, validation_loader, criterion)
        validation_losses.append(validation_loss / validation_dataset_size)
        validation_accuracies.append(validation_accuracy / validation_dataset_size)
        
        if validation_accuracy > best_model_accuracy:
            best_model_accuracy = validation_accuracy
            best_model_weights = model.state_dict()
        
        print("Epoch {}: train loss {}, train accuracy"
          " {}, validation loss {}, validation accuracy {}".format(
              epoch + 1,
              train_loss / train_dataset_size,
              train_accuracy / train_dataset_size,
              validation_loss / validation_dataset_size,
              validation_accuracy / validation_dataset_size
            )
        )
    print("Finished Training")
    time_elapsed = time.time() - since
    print(
            'Training complete in {:.0f}m {:.0f}s'.format(
            time_elapsed // 60, time_elapsed % 60
        )
    )
    print("Best model accuracy: ", best_model_accuracy)
    model.load_state_dict(best_model_weights)
    return train_losses, validation_losses, train_accuracies, validation_accuracies

In [20]:
def run_model(model, batch):
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    model.to(device)
    #inputs = batch
    #inputs = inputs.to(device, dtype=torch.float)
    inputs = batch.to(device, dtype=torch.float)
    outputs = model(inputs)
    #return outputs[0].cpu()
    return outputs.cpu()

In [21]:
def save_model(model, full=True, name='model'):
    if not full:
        torch.save(model.state_dict(), '{}_params.pkl'.format(name))
    else:
        torch.save(model, '{}.pkl'.format(name))
    return

In [22]:
def restore_model(name='model'):
    return torch.load('{}.pkl'.format(name))

In [23]:
train_df = load_data.load_text_data('../input/train.csv')

In [24]:
train_df_two_classes = train_df.copy()

In [25]:
train_df_two_classes.loc[train_df_two_classes['Id'] != 'new_whale', 'Id'] = 'not_new_whale'

In [26]:
train_df_two_classes.head(40)

Image             Id
0   0000e88ab.jpg  not_new_whale
1   0001f9222.jpg  not_new_whale
2   00029d126.jpg  not_new_whale
3   00050a15a.jpg      new_whale
4   0005c1ef8.jpg      new_whale
5   0006e997e.jpg      new_whale
6   000a6daec.jpg  not_new_whale
7   000f0f2bf.jpg      new_whale
8   0016b897a.jpg  not_new_whale
9   001c1ac5f.jpg  not_new_whale
10  001cae55b.jpg  not_new_whale
11  001d7450c.jpg      new_whale
12  00200e115.jpg      new_whale
13  00245a598.jpg      new_whale
14  002b4615d.jpg      new_whale
15  002f99f01.jpg      new_whale
16  00355ff28.jpg  not_new_whale
17  00357e37a.jpg  not_new_whale
18  003795857.jpg      new_whale
19  0041880bf.jpg      new_whale
20  0043da555.jpg      new_whale
21  00442c882.jpg  not_new_whale
22  00464ff65.jpg      new_whale
23  004775679.jpg  not_new_whale
24  004ae9e26.jpg      new_whale
25  004c0f43b.jpg      new_whale
26  004e8ad5b.jpg  not_new_whale
27  004f87702.jpg  not_new_whale
28  0050ef29d.jpg  not_new_whale
29  00514c876.jpg  not_new_whale
30  0052ce2f5.jpg  not_new_whale
31  00537ec91.jpg  not_new_whale
32  00570db6b.jpg  not_new_whale
33  005ce3100.jpg      new_whale
34  00600ce17.jpg      new_whale
35  006017ddf.jpg  not_new_whale
36  0060f764a.jpg  not_new_whale
37  006500b3d.jpg  not_new_whale
38  006506edf.jpg      new_whale
39  0067b3a20.jpg  not_new_whale

In [27]:
'''
image_size = 128
dataset = load_data.HumpbackWhalesDataset(
    train_df_two_classes,
    #train_df,
    #transform=load_data.transforms.ToTensor()
    #transform=ToTensor()
    transform=transforms.Compose(
        [
            #Rescale(int(image_size*1.25)),
            Rescale(int(image_size)),
            #RandomCrop(image_size),
            UnifyRescale(int(image_size)),
            ToTensor()
        ]
    )
)
'''

'\nimage_size = 128\ndataset = load_data.HumpbackWhalesDataset(\n    train_df_two_classes,\n    #train_df,\n    #transform=load_data.transforms.ToTensor()\n    #transform=ToTensor()\n    transform=transforms.Compose(\n        [\n            #Rescale(int(image_size*1.25)),\n            Rescale(int(image_size)),\n            #RandomCrop(image_size),\n            UnifyRescale(int(image_size)),\n            ToTensor()\n        ]\n    )\n)\n'

In [28]:
#image_size = 128
#image_size = 100
dataset = load_data.HumpbackWhalesDataset(
    train_df_two_classes,
    #train_df,
    #transform=load_data.transforms.ToTensor()
    #transform=ToTensor()
    transform=transforms.Compose(
        [
            transforms.Resize((IMAGE_W, IMAGE_H)),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]
            )
        ]
    )
)

In [29]:
dataset_loaders, dataset_sizes = prepare_loaders(dataset)

dataset_size:  25361
validation_subset_size:  10144


In [30]:
train_loader = dataset_loaders['train']
validation_loader = dataset_loaders['validation']
train_dataset_size = dataset_sizes['train']
validation_dataset_size = dataset_sizes['validation']

In [31]:
print(train_dataset_size)
print(validation_dataset_size)

15217
10144


In [32]:
print(train_loader)

In [33]:
train_iter = iter(train_loader)

Process Process-1:
Traceback (most recent call last):
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 96, in _worker_loop
    r = index_queue.get(timeout=MANAGER_STATUS_CHECK_INTERVAL)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/conne

In [34]:
print(type(train_iter))

<class 'torch.utils.data.dataloader._DataLoaderIter'>


In [35]:
#images, labels = train_iter.next()
sample = train_iter.next()
print(sample)

{'image': tensor([[[[-1.2445, -1.1932, -1.1418,  ..., -0.7993, -0.8164, -0.8678],
          [-1.1418, -1.1932, -1.1418,  ..., -0.8335, -0.8678, -0.9020],
          [-1.0733, -1.1418, -1.1075,  ..., -0.8507, -0.8849, -0.9192],
          ...,
          [-1.3302, -1.3644, -1.3987,  ..., -0.8678, -0.8678, -0.9020],
          [-1.3815, -1.3815, -1.3815,  ..., -0.9363, -0.9363, -0.9534],
          [-1.4329, -1.3815, -1.3815,  ..., -0.9020, -0.8849, -0.9020]],

         [[-0.7227, -0.6527, -0.5826,  ..., -0.1275, -0.1450, -0.2150],
          [-0.6176, -0.6527, -0.5826,  ..., -0.1625, -0.1800, -0.2500],
          [-0.5301, -0.6001, -0.5476,  ..., -0.1625, -0.2150, -0.2675],
          ...,
          [-0.9153, -0.9503, -0.9853,  ..., -0.1800, -0.1800, -0.1975],
          [-0.9678, -0.9678, -0.9503,  ..., -0.2850, -0.2850, -0.2850],
          [-0.9678, -0.9328, -0.9503,  ..., -0.2675, -0.2500, -0.2325]],

         [[-0.1138, -0.0441,  0.0256,  ...,  0.5311,  0.5136,  0.4962],
          [ 0.0082, 

In [36]:
'''
for i_batch, sample_batched in enumerate(train_loader):
    print(i_batch, sample_batched['image'].size(),
          sample_batched['label'])
    # observe 4th batch and stop.
    if i_batch == 0:
        plt.figure(figsize=(24, 24))
        show_whale_batch(sample_batched)
        plt.axis('off')
        #plt.ioff()
        plt.show()
        break
'''

"\nfor i_batch, sample_batched in enumerate(train_loader):\n    print(i_batch, sample_batched['image'].size(),\n          sample_batched['label'])\n    # observe 4th batch and stop.\n    if i_batch == 0:\n        plt.figure(figsize=(24, 24))\n        show_whale_batch(sample_batched)\n        plt.axis('off')\n        #plt.ioff()\n        plt.show()\n        break\n"

In [37]:
dataset.encoding

{'not_new_whale': 0, 'new_whale': 1}

In [38]:
#hwi_conv_neural_net = HWI_ConvNeuralNet()
#hwi_conv_neural_net.apply(init_weights)

In [39]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [40]:
print(device)

cuda:0


In [41]:
#hwi_conv_neural_net.to(device)

In [42]:
#criterion = nn.BCEWithLogitsLoss(reduction='sum')
#criterion = nn.BCEWithLogitsLoss()
#criterion = nn.BCELoss()
#optimizer = optim.Adam(hwi_conv_neural_net.parameters(), lr=0.001, betas=(0.9, 0.99))

In [43]:
num_of_epoch = 12
#train_losses = []
#train_accuracies = []
#validation_losses = []
#validation_accuracies = []

In [44]:
'''
torch.cuda.empty_cache()
since = time.time()
for epoch in range(num_of_epoch):
    epoch_train_accuracy = 0.0
    epoch_train_loss = 0.0
    correct_predicted_total = 0.0
    train_loss = 0.0
    #total_loss = 0.0
    #total = 0.0
    for i, data_batch in enumerate(train_loader, 0):
        
        inputs = data_batch['image']
        labels = data_batch['label']
        print("inputs: ", inputs)
        print("labels: ", labels)
        inputs = inputs.to(device, dtype=torch.float)
        labels = labels.to(device, dtype=torch.float)
        optimizer.zero_grad()
        
        outputs = hwi_conv_neural_net(inputs)

        print("outputs.size():\n", outputs.size())
        print("labels.size():\n", labels.size())
        print("outputs:\n", outputs)
        #print("outputs[:, 0]:\n", outputs[:, 0])
        print("labels:\n", labels)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item() * inputs.size(0)
        
        predicted = outputs > 0
        print("type(predicted): ", type(predicted))
        print("predicted:\n", predicted)

        #total += labels.size(0)
        labels = labels.data.byte()
        print("predicted == labels:\n", predicted == labels)
        #sum_of_correct_predicted = torch.sum((predicted == labels).all(1))
        sum_of_correct_predicted = torch.sum((predicted == labels))
        item = sum_of_correct_predicted.item()
        correct_predicted_total += item
        
    epoch_train_loss = train_loss / train_dataset_size
    epoch_train_accuracy = correct_predicted_total / train_dataset_size
    
    validation_loss, validation_accuracy = validate(hwi_conv_neural_net, validation_loader, criterion)
    
    epoch_validation_loss = validation_loss / validation_dataset_size
    epoch_validation_accuracy = validation_accuracy / validation_dataset_size
    
    print("Epoch {}: train loss {}, train accuracy"
          " {}, validation loss {}, validation accuracy {}".format(
              epoch + 1,
              epoch_train_loss,
              epoch_train_accuracy,
              epoch_validation_loss,
              epoch_validation_accuracy
        )
    )
    train_losses.append(epoch_train_loss)
    train_accuracies.append(epoch_train_accuracy)
    validation_losses.append(epoch_validation_loss)
    validation_accuracies.append(epoch_validation_accuracy)
            
print("Finished Training")
time_elapsed = time.time() - since
print(
    'Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60
    )
)
'''

'\ntorch.cuda.empty_cache()\nsince = time.time()\nfor epoch in range(num_of_epoch):\n    epoch_train_accuracy = 0.0\n    epoch_train_loss = 0.0\n    correct_predicted_total = 0.0\n    train_loss = 0.0\n    #total_loss = 0.0\n    #total = 0.0\n    for i, data_batch in enumerate(train_loader, 0):\n        \n        inputs = data_batch[\'image\']\n        labels = data_batch[\'label\']\n        print("inputs: ", inputs)\n        print("labels: ", labels)\n        inputs = inputs.to(device, dtype=torch.float)\n        labels = labels.to(device, dtype=torch.float)\n        optimizer.zero_grad()\n        \n        outputs = hwi_conv_neural_net(inputs)\n\n        print("outputs.size():\n", outputs.size())\n        print("labels.size():\n", labels.size())\n        print("outputs:\n", outputs)\n        #print("outputs[:, 0]:\n", outputs[:, 0])\n        print("labels:\n", labels)\n        loss = criterion(outputs, labels)\n        loss.backward()\n        optimizer.step()\n        \n        trai

In [45]:
#resnet18 = models.resnet18(pretrained=True)

In [46]:
#resnet18

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Co

In [47]:
features_num = resnet18.fc.in_features

In [48]:
features_num

512

In [49]:
#resnet18.fc = nn.Linear(features_num, BATCH_SIZE)
#resnet18.fc = nn.Linear(BATCH_SIZE, 2048)
#resnet18.fc = nn.Linear(2048, BATCH_SIZE)
#resnet18.fc = nn.Sigmoid()

In [50]:
resnet18.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (conv2): Co

In [51]:
learning_rate = 0.001

In [52]:
resnet18.state_dict().keys()

odict_keys(['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.num_batches_tracked', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.num_batches_tracked', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.bn1.running_mean', 'layer2.0.bn1.running_var', 'layer2.0.bn1.num_batches_tracked', 'layer2.0.conv2.weight', 'layer2.0.bn2.weight', 'layer2.0.bn2.bias', '

In [53]:
#resnet18.state_dict()['conv1.weight'].size()
#resnet18.state_dict()['fc.weight'].size()

In [54]:
#criterion = nn.CrossEntropyLoss()
#optimizer = optim.SGD(resnet18.parameters(), lr=learning_rate, momentum=0.9)

In [55]:
criterion = nn.BCELoss()
optimizer = optim.Adam(resnet18.parameters(), lr=0.001, betas=(0.9, 0.99))

In [56]:
train_rezult_metrics = train_model(
    num_of_epoch,
    #hwi_conv_neural_net,
    resnet18,
    dataset_loaders,
    dataset_sizes,
    criterion,
    optimizer
)

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[0, 1, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1],
        [1, 0, 0,  ..., 0, 1, 1],
        ...,
        [0, 1, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1],
        [0, 1, 0,  ..., 0, 0, 1]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(433, device='cuda:0')

item.size():  433
item:
 433
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 1, 1],
        [1, 1, 0,  ..., 0, 1, 1],
        [1, 1, 1,  ..., 0, 1, 1],
        ...,
        [1, 1, 0,  ..., 0, 0, 1],
        [1, 0, 0,  ..., 1, 1, 1],
        [1, 0, 0,  ..., 1, 1, 1]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(518, device='cuda:0')

item.size():  518
item:
 518
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(610, device='cuda:0')

item.size():  610
item:
 610
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(671, device='cuda:0')

item.size():  671
item:
 671
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(702, device='cuda:0')

item.size():  702
item:
 702
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(672, device='cuda:0')

item.size():  672
item:
 672
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 1, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(705, device='cuda:0')

item.size():  705
item:
 705
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(416, device='cuda:0')

item.size():  416
item:
 416
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 1, 1, 1, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(544, device='cuda:0')

item.size():  544
item:
 544
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(578, device='cuda:0')

item.size():  578
item:
 578
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 0, 1, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(480, device='cuda:0')

item.size():  480
item:
 480
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(479, device='cuda:0')

item.size():  479
item:
 479
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 1, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(544, device='cuda:0')

item.size():  544
item:
 544
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(609, device='cuda:0')

item.size():  609
item:
 609
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(767, device='cuda:0')

item.size():  767
item:
 767
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(799, device='cuda:0')

item.size():  799
item:
 799
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(672, device='cuda:0')

item.size():  672
item:
 672
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 1, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(641, device='cuda:0')

item.size():  641
item:
 641
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(672, device='cuda:0')

item.size():  672
item:
 672
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 1, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(514, device='cuda:0')

item.size():  514
item:
 514
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 1, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(702, device='cuda:0')

item.size():  702
item:
 702
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 1, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(638, device='cuda:0')

item.size():  638
item:
 638
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 1, 1, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 1, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(510, device='cuda:0')

item.size():  510
item:
 510
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
        0, 1, 0, 0, 0, 1, 1, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(481, device='cuda:0')

item.size():  481
item:
 481
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(800, device='cuda:0')

item.size():  800
item:
 800
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 1, 1, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 1, 0, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(672, device='cuda:0')

item.size():  672
item:
 672
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(607, device='cuda:0')

item.size():  607
item:
 607
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(609, device='cuda:0')

item.size():  609
item:
 609
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(639, device='cuda:0')

item.size():  639
item:
 639
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 1, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(640, device='cuda:0')

item.size():  640
item:
 640
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 0, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 0, 1, 0, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(640, device='cuda:0')

item.size():  640
item:
 640
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 0, 1, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 1], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(544, device='cuda:0')

item.size():  544
item:
 544
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(704, device='cuda:0')

item.size():  704
item:
 704
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(672, device='cuda:0')

item.size():  672
item:
 672
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 1

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(640, device='cuda:0')

item.size():  640
item:
 640
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 1, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(511, device='cuda:0')

item.size():  511
item:
 511
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([1, 1, 0, 0, 0

predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 1, 0, 0], device='cuda:0', dtype=torch.uint8)

sum_of_correct_predicted.size():
 torch.Size([])
sum_of_correct_predicted:
 tensor(671, device='cuda:0')

item.size():  671
item:
 671
predicted.size(): torch.Size([32, 32])
predicted:
 tensor([[1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        ...,
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)

labels.size(): torch.Size([32])
labels:
 tensor([0, 0, 0, 0, 1

Process Process-3:
Traceback (most recent call last):
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/uldo/work/kaggle/competitions/Humpback_Whale_Identification/code/load_data.py", line 242, in __getitem__
    image = Image.open(path_to_image_file).convert('RGB')
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/PIL/Image.py", line 892, in convert
    self.loa

Traceback (most recent call last):
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-f4184539a75a>", line 8, in <module>
    optimizer
  File "<ipython-input-19-6e493d28ff43>", line 24, in train_model
    validation_loss, validation_accuracy = one_epoch_validate(model, validation_loader, criterion)
  File "<ipython-input-17-67ff1c88a7ec>", line 8, in one_epoch_validate
    for data_batch in data_loader:
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 330, in __next__
    idx, batch = self._get_batch()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 309, in _get_batch
    return self.data_queue.get()
  File "/home/uldo/miniconda3/envs/DS-New/lib/python3.6/multiprocessing/queues.py", line 335, in get
    res = self

KeyboardInterrupt: 

In [ ]:
train_losses, validation_losses, train_accuracies, validation_accuracies = train_rezult_metrics

In [ ]:
plt.plot(np.arange(len(train_losses)), train_losses, label='train')
plt.plot(np.arange(len(validation_losses)), validation_losses, label='validation')
plt.legend()
plt.title("loss by epoch")
plt.show()

plt.plot(np.arange(len(train_accuracies)), train_accuracies, label='train')
plt.plot(np.arange(len(validation_accuracies)), validation_accuracies, label='validation')
plt.legend()
plt.title("accuracy by epoch")
plt.show()

In [ ]:
train_rezult_metrics