In [14]:
import os
import tensorflow as tf
import skimage

In [2]:
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])

In [3]:
result = tf.multiply(x1, x2)

In [4]:
print(result)

Tensor("Mul:0", shape=(4,), dtype=int32)


In [5]:
sess = tf.Session()

In [6]:
print(sess.run(result))

[ 5 12 21 32]


In [7]:
sess.close()

In [8]:
with tf.Session() as sess:
    output = sess.run(result)
    print(output)

[ 5 12 21 32]


In [9]:
config = tf.ConfigProto(log_device_placement=True)

In [10]:
with tf.Session() as sess:
    output = sess.run(result)
    print(output)

[ 5 12 21 32]


In [11]:
config = tf.ConfigProto(allow_soft_placement=True)

In [12]:
ROOT_PATH = 'belgium-traffic/'

In [15]:
def load_data(data_directory):
    directories = [
        d for d in os.listdir(data_directory)
        if os.path.isdir(os.path.join(data_directory, d))
    ]
    labels = []
    images = []
    for d in directories:
        label_directory = os.path.join(data_directory, d)
        file_names = [os.path.join(label_directory, f)
                      for f in os.listdir(label_directory)
                      if f.endswith('.ppm')
                ]
        for f in file_names:
            images.append(skimage.io.imread(f))
            labels.append(int(d))
        
    return images, names